version: '3'
services:
    nodeserver:
        build:
          context: ./node
        ports:
            - "6001:6001" 
        networks:
            - example-net  
    nginx:
        #restart : always
        build:
          context: ./nginx
        ports:
            - "80:80" 
        depends_on:
            - nodeserver
        networks:
            - example-net
    react-app:
       image: react-app-image
       container_name: app-frontend  
       networks:
        - example-net
       ports:
        - "3000:3000"
networks:
  example-net:
    external: true
