version: '3'
services:
    nodeserver:
        build:
          context: ./app
        ports:
            - "6001:6001" 
        networks:
            - example-net  
    nginx:
        restart : always
        build:
          context: ./nginx
        ports:
            - "80:80" 
        depends_on:
            - nodeserver
        networks:
            - example-net

networks:
  example-net:
    external: true
